# Generated by Django 5.2.16 on 2026-07-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_exam_type'),
        ('users', '0003_user_email_verified_user_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='target_students', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='target_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_students_old', to='exams.exam'),
        ),
    ]
