# Generated by Django 5.2.16 on 2026-07-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_copy_target_exam_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='target_exam',
        ),
    ]
