# Generated by Django 5.2.16 on 2026-07-10 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_attempt', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank'],
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
