# Generated by Django 5.2.16 on 2026-07-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('BPSC', 'BPSC'), ('CTET', 'CTET'), ('STET', 'STET'), ('BANKING', 'Banking'), ('RAILWAY', 'Railway'), ('POLICE', 'Police'), ('DEFENCE', 'Defence'), ('STATE_GOVT', 'State Government'), ('ENGINEERING', 'Engineering'), ('MEDICAL', 'Medical'), ('CA', 'Chartered Accountancy')], default='SSC', max_length=20),
        ),
    ]
