# Generated by Django 5.2.16 on 2026-07-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='test',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='test',
            name='price',
        ),
        migrations.AddField(
            model_name='test',
            name='credit_cost',
            field=models.PositiveIntegerField(blank=True, help_text='Admin-set credit cost, required when is_paid=True', null=True),
        ),
    ]
