# Generated by Django 5.2.16 on 2026-07-16 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_platformsettings_remove_order_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credits', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True, help_text='Inactive plans are hidden from students but kept for history')),
            ],
            options={
                'db_table': 'recharge_plan',
                'ordering': ['amount'],
            },
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='credits_per_rupee',
        ),
        migrations.AlterField(
            model_name='order',
            name='credits_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Snapshotted from RechargePlan.credits at order-creation time'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.rechargeplan'),
        ),
    ]
